# Generated by Django 4.2.6 on 2023-11-15 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0002_alter_paragraph_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Framework',
        ),
    ]
