# Generated by Django 4.2.6 on 2023-12-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0005_stack_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stack',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/stack-images/'),
        ),
    ]
