# Generated by Django 4.2.6 on 2023-11-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0001_initial'),
        ('languages', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='frameworks',
            field=models.ManyToManyField(blank=True, to='frameworks.framework'),
        ),
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(blank=True, to='languages.language'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='projects.tag'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='projects.technology'),
        ),
    ]
