# Generated by Django 4.2.6 on 2023-11-16 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_frameworks_project_languages_project_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
