# Generated by Django 4.2.6 on 2023-11-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0001_initial'),
        ('projects', '0003_remove_project_technologies_delete_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='technologies.technology'),
        ),
    ]
