# Generated by Django 4.2.6 on 2023-11-06 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_frameworks_alter_project_languages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created',
        ),
    ]
