# Generated by Django 4.2.6 on 2023-11-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
