# Generated by Django 4.2.6 on 2023-11-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0001_initial'),
        ('about_me', '0004_stack_frameworks_stack_image_stack_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='technologies',
            field=models.ManyToManyField(to='technologies.technology'),
        ),
    ]
